landing:
  path: /
  controller: App\Controller\LandingController::landingPage

register:
  path: /register
  controller: App\Controller\RegisterController::signUp
  
login:
  path: /login
  controller: App\Controller\LoginController::login

deconnection:
  path: /deconnection
  controller: App\Controller\LandingController::deconnectionUser

update_password:
  path: /updatePassword/{username}
  controller: App\Controller\AccountSettingsController::changePwd

profil:
  path: /profil/{username}
  controller: App\Controller\ProfilController::redirectToProfilPage

addPost:
  path: /newPost/{usenrame}
  controller: App\Controller\PostController::newPost

validatedNewPost:
  path: /newPost/add/{usenrame}
  controller: App\Controller\PostController::validatedNewPost

consultPost:
  path: /consultPost/{username}
  controller: App\Controller\PostController::consultPost

changePost:
  path: /changePost/{username}
  controller: App\Controller\PostController::changePost

my_cars:
  path: /mycars/{username}
  controller: App\Controller\CarsController::carsPage

my_new_cars:
  path: /newCar/add/{username}
  controller: App\Controller\CarsController::addNewcar

account_settings:
  path: /accountSettings/{username}
  controller: App\Controller\AccountSettingsController::editAccount

search:
  path: /search
  controller: App\Controller\ProfilController::searchPage

book:
  path: /book/{id_announcement}
  controller: App\Controller\BookController::bookPage

bookValid:
  path: /book/valid/{id_announcement}
  controller: App\Controller\BookController::bookValidPage

removeCar:
  path: /mycars/removeCar/{username}
  controller: App\Controller\CarsController::removeCar

updatePrice:
  path: /mycars/updatePrice/{username}
  controller: App\Controller\PostController::updatePrice

error:
  path: /error404
  controller: App\Controller\LandingController::error404Page 
